version: '3.8'

services:
  laravel:
    build:
      context: ../auth-system
      dockerfile: Dockerfile
    container_name: laravel-backend
    volumes:
      - ../auth-system:/var/www
    expose:
      - "9000"                   # Expose PHP-FPM for nginx
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"                # Laravel backend served here
    volumes:
      - ../auth-system:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  vue:
    build:
      context: ../vue-auth-system
      dockerfile: Dockerfile
    container_name: vue-frontend
    volumes:
      - ../vue-auth-system:/app
    ports:
      - "8080:8080"              # Vue dev server port mapping
    environment:
      - VITE_API_BASE=http://localhost:8000/api

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"              # Host 3307 -> container 3306 (avoid conflict with local mysql)
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
