version: '3.8'

services:
  laravel:
    build:
      context: ../auth-system
      dockerfile: Dockerfile
    container_name: laravel-backend
    volumes:
      - ../auth-system:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ../auth-system:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  vue:
    build:
      context: ../vue-auth-system
      dockerfile: Dockerfile
    container_name: vue-frontend
    volumes:
      - ../vue-auth-system:/app
      - /app/node_modules  # Avoid node_modules overwrite by volume
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix for watching files on Windows
    command: npm run dev -- --host 0.0.0.0
    # No depends_on needed here unless you want it to wait for laravel/nginx

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
